### ISSUE TITLE
[Tracking Issue] Update cross container to go1.15

### ISSUE THREAD

**Issue by hasheddan** [upbound/build#108]
Go 1.15 [has been released](https://blog.golang.org/go1.15). We should update the cross container to use this new Go version. Previously, we have waited for a subsequent patch version after minor releases, so that may be desirable here as well.

**Comment by AaronME** [comment]
go1.16 has been released and adds support for Apple Silicon. Can we update to that instead/too?

**Comment by jbw976** [comment]
Looks like an effort was started on this with #122, but it didn't get to the finish line.  There may be 2 things to take care of here all at once:

* Remove the allowlist altogether that has to constantly be manually updated when new versions of go come out, as suggested by @muvaf [here](https://github.com/upbound/build/pull/122/files#r552025783)
  * this would allow folks to use the golang version that is on their machine
* In the cross build container, update the version it internally uses to be 1.16: https://github.com/upbound/build/blob/master/cross/Dockerfile#L48
  * this would be constant and repeatable usage of a consistent build environment within all our CI (the cross build container brings it's own golang with it, it doesn't depend on the environment running it)

**Comment by haarchri** [comment]
outdated - we will Close this issue - feel free to reopen If needed
