### ISSUE TITLE
DOCKER_REGISTRY is not respected when given as env var

### ISSUE THREAD

**Issue by muvaf** [upbound/build#176]
### What problem are you facing?

If I build with `make build DOCKER_REGISTRY=muvaf`, the variable makes it to `package/crossplane.yaml`

However, if I do `export DOCKER_REGISTRY=muvaf && make build` it won't be effective and I'll see `crossplane/` in `package/crossplane.yaml`

The provider is https://github.com/crossplane-contrib/provider-jet-linode and this issue describes what we're trying to do https://github.com/thechangelog/changelog.com/pull/399 if it helps.

### How could Upbound help solve your problem?

There might be something overriding the env var but not the explicit variable passed to `make` command.

**Comment by hasheddan** [comment]
@muvaf I see `DOCKER_REGISTRY := crossplane` in the Makefile in https://github.com/crossplane-contrib/provider-jet-linode/blob/b1c167a504f3b6676c5488042b4fef127d4a6e27/Makefile#L52 -- using `DOCKER_REGISTRY ?= crossplane` should make the exported variable honored.

**Comment by gerhard** [comment]
https://github.com/crossplane-contrib/provider-jet-linode/commit/8880f939f11a2c354d59d707c26af16a07fb26f3
