### ISSUE TITLE
Facing "unknown architecture error" while building Crossplane on arm64 platform

### ISSUE THREAD

**Issue by odidev** [upbound/build#178]
I am getting an **unknown architecture error** while building [crossplane](https://github.com/crossplane/crossplane) on aarch64 platform, which uses **upbound/build** as a submodule.

I have done the below changes to resolve the issues.

```
diff --git a/makelib/common.mk b/makelib/common.mk
index 800bacc..8ffae43 100644
--- a/makelib/common.mk
+++ b/makelib/common.mk
@@ -126,6 +126,11 @@ SAFEHOSTARCH := amd64
 TARGETARCH := amd64
 endif

+ifeq ($(HOSTARCH),aarch64)
+SAFEHOSTARCH := arm64
+TARGETARCH := arm64
+endif

```

It is necessary to add these changes to build packages on arm64 platform which uses **upbound/build** as a submodule. I will raise a PR if the above changes looks good.

**Comment by odidev** [comment]
It is required to add this change to run in the arm64 platform. If required, I am happy to raise a PR.

**Comment by negz** [comment]
Thanks! I was facing this too just now.
