### ISSUE TITLE
golangci-lint version

### ISSUE THREAD

**Issue by tomas-mota** [upbound/build#218]
### Description

It seems like when using go 1.19 (not sure it also happens with go 1.18), `make lint` fails with the following error:

*Can't run linter unused: buildir: failed to load package goarch: could not load export data: cannot import "internal/goarch" (unknown iexport format version 2), export data is newer version - update tool*

In order to observe this behaviour, run `make lint` in https://github.com/crossplane/provider-template. Try updating the golangci-lint version in golang.mk to 1.50 from 1.31 and it will work (albeit with deprecation warnings)

**Comment by cychiang** [comment]
I think the issue is related to the PR #206

**Comment by tomas-mota** [comment]
sorry, I'll close this
